### ISSUE TITLE
File selection (ease of use)

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/LaunchCamPlus#10]
Ease of use thingo.
![image](https://user-images.githubusercontent.com/37796393/55663444-763a8a80-5865-11e9-930f-6cac1f695a3b.png)
Instead of separating them you should just have it open either no matter what.
So have a "Supported Files (*.rarc; *.arc; *.bcam) instead.

**Comment by SuperHackio** [comment]
Oh yeah
This is one of those things that I had in mind, was going to do, got distracted, and then forgot about

I'll get to it eventually
lol

**Comment by SuperHackio** [comment]
Fixed in LCP 2.2.0.0
