### ISSUE TITLE
Camera IDs are able to be capitalised.

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/LaunchCamPlus#14]
The game recognises c:000a and c:000A as different beings, one being valid and the other invalid respectively. Writing 0x0a goes against common intuition as hexadecimal values are generally written as capital letters.

Could easily be fixed by correcting the issue upon saving.

I struggled with this issue in Dossun and discovered it also exists in LCP through a lot of trial and error with camera priorities. Fixing the capitalization fixed the issue.

**Comment by SuperHackio** [comment]
Sure, I'll fix this sometime today
