### ISSUE TITLE
Bob-Omb Battlefield in SMG1

### ISSUE THREAD

**Issue by SuperKoopatlasMaster** [SuperHackio/LaunchCamPlus#15]
ok your launchCam software just looks awesome. i cant figure out how in sweet sweet galaxy that i added bobomb to
as to why when i climb and go around the mountain that cameras wont follow mario and like halfway up and around the mountain seems to change view to 45 degree offset ?
i am hoping with your software i can fix this

**Comment by SuperKoopatlasMaster** [comment]
[[C01] Bob-omb Battlefield.zip](https://github.com/SuperHackio/LaunchCamPlus/files/8189922/C01.Bob-omb.Battlefield.zip)

**Comment by SuperKoopatlasMaster** [comment]
[BeltConveyerExGalaxyScenario.zip](https://github.com/SuperHackio/LaunchCamPlus/files/8189927/BeltConveyerExGalaxyScenario.zip)

**Comment by SuperHackio** [comment]
Hello!
You have only sent me the model files and the scenario files... Without the map files, I cannot do much.

The map file should be `StageData/BeltConveyerExGalaxy.arc`

After you send it here, I can provide a fix
