### ISSUE TITLE
Throws error when opening a blank BCAM

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/LaunchCamPlus#3]
Example:
[SurvivalExPackunZoneMap.zip](https://github.com/SuperHackio/LaunchCamPlus/files/2660343/SurvivalExPackunZoneMap.zip)

**Comment by SuperHackio** [comment]
This should fix it:
![error](https://user-images.githubusercontent.com/44330283/49701985-2514d580-fba8-11e8-95f7-4bfdfcb83044.png)
