### ISSUE TITLE
Isolate commands.

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/LaunchCamPlus#5]
Basically, when trying to select all of a particular setting with CTRL-A it will also add a camera, which is really annoying. Isolating the keyboard shortcuts to outside of text boxes would fix this.

**Comment by SuperHackio** [comment]
Shortcuts that would overlap such actions now require you to hold Shift:
![image](https://user-images.githubusercontent.com/44330283/49702934-8db57f80-fbb3-11e8-9ba0-1bf8f92b693d.png)

**Comment by ghost** [comment]
*when trying to select all of a particular setting with CTRL-A it will also add a camera*

Still happens for me...Also, if I press Shift, it does nothing, and CTRL+Shift still adds a camera.

Does the version still have to be released?
