### ISSUE TITLE
s:xxxx/c:xxxx doesn't have a name like the other cameras.

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/LaunchCamPlus#6]
These are the spawn cameras so they should really have a name. If this is done to avoid confusion between multiple spawn cameras, it could instead be shown as Spawn:xxxx. The same can be said for c:xxxx, where it could be Camera:xxxx.

**Comment by SuperHackio** [comment]
I assume you mean in the Camera list. 
So basically, the Camera Areas and Spawn camera's would display actual names instead of just "C" or "S" (Similar to how some event cameras are translated from Japanese)

**Comment by gayfrogog** [comment]
Yeah it just seems odd for them to not be displayed like the Japanese names.

**Comment by SuperHackio** [comment]
Fixed in LCP 2.2.0.0
